### ISSUE TITLE
Many to Many

### ISSUE THREAD

**Issue by nickretallack** [didit-tech/FastLegS#11]
How do I query through a join table with this?

**Comment by malkomalko** [comment]
an example of how to do this... take a look at the tests for usage examples and let me know if you have any questions.

``` javascript
var Role = FastLegS.Base.extend({
  tableName: 'roles',
  primaryKey: 'id'
});

var User = FastLegS.Base.extend({
  tableName: 'users',
  primaryKey: 'id',
  many: [
    { 'roles': Role, joinOn: 'user_roles.role_id' }
  ]
});

User.find({ 'first.in': ['Rob', 'Mike', 'Jane'] }, {
  only: ['id', 'first', 'last'],
  order: ['-first'],
  include: { 'roles': {} }
}, function(err, results) {
  //
});
```

**Comment by nickretallack** [comment]
Is that really enough information?  How does it know with what key to join the user_roles table to the User table?

**Comment by malkomalko** [comment]
we make an assumption that it's joining to the table's primaryKey

Thus the role_id column in the user_roles join table, would find the role where role.id == user_roles.role_id

**Comment by nickretallack** [comment]
You need two joins here though.  One of them would presumably be user.id = user_roles.user_id, but that is never mentioned in the source here.

**Comment by gahula** [comment]
I think a good idea would be to give the flexibility of  joinOn: 'table1.column1 = table2.column2'
