### ISSUE TITLE
Quote doesn't quote.  SQL injection is easy.

### ISSUE THREAD

**Issue by nickretallack** [didit-tech/FastLegS#14]
All it does is put quotes around things.  It doesn't escape inner quotes.  If you pass it a string like "'lol'" it will cause an error.

```
var quote = exports.quote = function(value) { ...
    return "'" + value + "'";
... };
```

This might be more appropriate:

```
var quote = exports.quote = function(value) { ...
    return "'" + value.replace(/'/g,"\\'") + "'";
... };
```

**Comment by nickretallack** [comment]
Actually wait a sec, why are you quoting it yourself anyway?  You could just use the quoting features in the pg library you're already using.  Just generate $1 $2 etc in the query text and pass in an array of values after it.

**Comment by malkomalko** [comment]
good idea.. will also take a look at your many -> many early next week when we have time to hack on this.

also, pull requests don't hurt :)
