### ISSUE TITLE
Select statement with limit and order.

### ISSUE THREAD

**Issue by railwaymen** [didit-tech/FastLegS#17]
In https://github.com/didit-tech/FastLegS/blob/master/lib/fast_legs/statements.js#L21 file
In line   ' return stmt + join + where + limit + offset + order + ';';'   limit and offset should be at the end on the sql statement. 
Now it is impossible to use order statement with limit.

Thanks.

**Comment by thadclay** [comment]
Thanks for the heads up. Its fixed now.
