### ISSUE TITLE
MySQL support VIA node-mysql

### ISSUE THREAD

**Issue by pifantastic** [didit-tech/FastLegS#19]
Is there any reason not to abstract the Client to be swapped with other DB modules, like node-mysql?  I know that mysql and postgres aren't 100% compatible, so maybe it's worth the effort. 

I really like FastLegS but my requirements have switched to MySQL.  If anyone thinks it's a good idea to abstract the Client to be either MySQL or Postgres, I'll happily do that work.  Otherwise I will fork FastLegS and create a MySQL version.

Thoughts?

**Comment by dogeared** [comment]
I know it's been a while, but the latest release now supports mysql as well as postgres. There is some abstraction work to be done for sure, but it is functional. ;)
