### ISSUE TITLE
belongs_to / one

### ISSUE THREAD

**Issue by malkomalko** [didit-tech/FastLegS#2]
should have the ability to use belongs_to/one since we have many and many through working.

**Comment by pifantastic** [comment]
I'm mega interested in this feature.  Has there been any movement on this?  Any knowledge to share before I take a crack at it?

**Comment by malkomalko** [comment]
we worked on this about a week ago but things came up.  I see that you took a stab at putting some operations in.  If you wanted to take a crack at it that'd be great.

just make sure belongsTo and One returns back an Object and not an array, and it can handle situations where there is nothing there (returning a blank object).

It'd be nice if you can tack on to the integration test.

Cheers!

**Comment by pifantastic** [comment]
Thanks @malkomalko.  The Object vs. Array return is not something I handled properly, so I've fixed that.  I'm now adding integration tests.  Will pull request when I feel it's in a good spot.  Thanks!

https://github.com/pifantastic/FastLegS/commit/d8a0b45208f0e23f9d8bf8e5ddf4720a6fa3a6be

**Comment by nickretallack** [comment]
Wait, you have many through working?  How?

**Comment by pifantastic** [comment]
Hi @nickretallack, I do have a basic "many" relationship working as seen here: https://github.com/pifantastic/FastLegS/blob/master/lib/fast_legs/base.js#L154

I've begun writing an integration test that uses a "many" relationship here: https://github.com/pifantastic/FastLegS/blob/master/test/integration/integration_test.js#L92

I've been working on other things lately but I'm getting back into my work with FastLegS so hopefully I will be ready for a pull of these changes into the main repo.

**EDIT**

I ended up taking a different direction that no longer required these relationships so the above links no longer reference the relevant code.
