### ISSUE TITLE
Many to many error on where clause

### ISSUE THREAD

**Issue by jonatasoliveira** [didit-tech/FastLegS#20]
I'm trying to do a many to many relation between the tables account and user, via account_user. My tables are:

Account
- account_id
- account_name

User
- user_id
- user_name

AccountUser
- account_id
- user_id

What I did:

``` javascript
var User = FastLegS.Base.extend({
  tableName: 'user',
  primaryKey: 'user_id',
  _fields: [
    {column_name: 'user_id'},
    {column_name: 'user_name'},
  ],
  many: [
    {'accounts': Account, joinOn: 'account_user.user_id'}
  ],
});

var Account = FastLegS.Base.extend({
  tableName: 'account',
  primaryKey: 'account_id',
  _fields: [
    {column_name: 'account_id'},
    {column_name: 'account_name'},
  ],
  many: [
    {'users': User, joinOn: 'account_user.account_id'}
  ],
});
```

With the above tables I'm running this code:

``` javascript
Account.findOne(75, {include: {'users': {}}}, function(err, result) {
    // Do something...
});
```

I've printed all the queries to see what was happening and I found that the Where clause is selecting the the id in the same table, like this:

``` sql
SELECT "user".*
FROM "user"
INNER JOIN "account_user" ON "user".user_id="account_user".user_id
WHERE "user".user_id = 75;
```

The correct query should be:

``` sql
SELECT "user".*
FROM "user"
INNER JOIN "account_user" ON "user".user_id="account_user".user_id
WHERE "account_user".account_id = 75;
```

How do I correct this behavior?

PS: In the meantime I'm trying to hack the source trying to figure out how to do this.

**Comment by dogeared** [comment]
Sorry it's taken so long to respond.

This issue has been resolved. We've implemented a new syntax for many-to-many joins.

You can see and example in the README as well as in the tests.
