### ISSUE TITLE
Newer versions of node break the required postgres module

### ISSUE THREAD

**Issue by GothAck** [didit-tech/FastLegS#26]
I've taken a look and as the binary buffer in newer versions of node have changed the postgres module needs updating to > 0.6.5.

I can provide a patch, but not right now (have run some queries against FastLegS running with 0.6.6 and seems ok, but need to test more)

**Comment by eldavido** [comment]
Any updates on this? Think I'm hitting this, too.

**Comment by thadclay** [comment]
Fixed with b3d303054f1c3cce590453ccc3495314f90643e6. Grab the latest version from npm.
