### ISSUE TITLE
Many to many?

### ISSUE THREAD

**Issue by pvencill** [didit-tech/FastLegS#28]
Is there Many To Many support right now?  

I tried defining a set of models in a way that I thought would work, but when I try and call a 'find' I get told that my 'id' is ambiguous.  I don't have the freedom to change my db schema to make every table use a different column name for Id, and the query that's passed looks right _except_ for the fact that id isn't scoped.  

Are there docs somewhere that can tell me how to do m2m?

**Comment by dogeared** [comment]
Hey pvencill,

Sorry it's taken us so long to respond. Please take a look at the laters version. The README on the github page now includes a many-to-many example.

We've implemented a new syntax that I think makes things much clearer.
