### ISSUE TITLE
README Update?

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#36]
Hi guys, I am still looking forward to the README/Examples. Are you still doing this?

**Comment by thadclay** [comment]
Yes we are. We should have some examples up soon.

On Aug 14, 2012, at 8:11 PM, gahula notifications@github.com wrote:

Hi guys, I am still looking forward to the README/Examples. Are you still
doing this?

—
Reply to this email directly or view it on
GitHubhttps://github.com/didit-tech/FastLegS/issues/36.
