### ISSUE TITLE
$or doesn't seem to work

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#40]
'$or': { 
    'id': 56,
    'name': 'harry'
}

'$or': { 
    'id.equal.equals': 56,
    'name.equals': 'harry'
}

tried both of these methods for an OR select statement, didn't return anything all AND statements work fine.

{
 'id': 56
}

**Comment by thadclay** [comment]
It should be this

'$or': { 
'id.equals': 56,
'name.equals': 'harry'
}

**Comment by gahula** [comment]
the above was a typo that should have been

'$or': {
'id.equals': 56,
'name.equals': 'harry'
}

exactly waht you have NOT equal.equals.... I am assuming it is a genuine bug
