### ISSUE TITLE
$or doesn't seem to work

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#41]
'$or': {
'id': 56,
'name': 'harry'
}

'$or': {
'id.equals': 56,
'name.equals': 'harry'
}

tried both of the above methods for an OR select statement, didn't return anything. All AND statements work fine.

{
'id': 56
}

**Comment by thadclay** [comment]
As I wrote in issue #40 the proper syntax is

'$or': { 
'id.equals': 56,
'name.equals': 'harry'
}

Take a look at commit 1160846 which has a complete example of '$or' working.

**Comment by gahula** [comment]
We will have to leave it closed, i tried that.
