### ISSUE TITLE
Clearing values in database using null, '' or undefined does work

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#42]
When updating a field to a null i.e. clearing its contents. I always get an error.
I have tried null, '', undefined, 'null', 'undefined'. The below error was from a timestamp field i wanted to clear. I get this with and type of field I want to clear using the "empty" values above.

How do you clear a field usign fastlegs?

{ [error: invalid input syntax for type timestamp with time zone: ""]
  length: 141,
  name: 'error',
  severity: 'ERROR',
  code: '22007',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: '.\src\backend\utils\adt\datetime.c',
  line: '3560',
  routine: 'DateTimeParseError' }

**Comment by thadclay** [comment]
In the example you provided you tried to set a timestamp column to an empty string which correctly threw the error that you are seeing. Below are two examples that I tested with the schema that is provided with the project. They both work.

``` javascript
Post.update({ 'id': 4 }, {
  'blurb': null
}, function(err, results) {
  //do something here         
});

Comment.update({ 'id': 8 }, { 
  'created_at': null 
}, function(err, result) { 
  //do something here      
});
```
