### ISSUE TITLE
Not Equal to Null Not Working

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#53]
var where = {
    '$or': { 
        'account_id.equals': 1,
        'recipient_id.equals': 1
    },
    'approved_on.ne': null
};

approved on is a timestamp field.

Can null not be checked against a timestamp field? THe query doesn't return any rows with that line

**Comment by thadclay** [comment]
Please replicate this in a test and I'll take a look. Thanks.

**Comment by gahula** [comment]
How would I go about doing this so that you can verify it?
Are you saying that the above code should run without any issue?

**Comment by gahula** [comment]
PostgreSQL
+++++++++

Column (Type)

connection_id (integer)
recipient_id (integer)
account_id (integer)
approved_on (timestamp with time zone)
is_private (boolean)
id (integer)
started_on (timestamp with time zone)

Node.js
++++++

Test 1. 
var where = {
   'approved_on.ne': null
};

-- The above DOES NOT work (approved_on column has 2013-03-17 22:30:03.228+00 value in it)
   i.e. It should return the row since it is not null but doesn't.

Test 2. 
var where = {
   'approved_on': null
};

-- The above DOES work (approved_on column has NULL value in it)

Test 3.
 var where = {
   'is_private': false
};

-- The above DOES work (is_private column has FALSE value in it)

It seems that ne (not equal) does not work with timestamp.
Is it because of FastLegs or PostgreSQL ?

**Comment by gahula** [comment]
I jsut used 'approved_on.lt': <very low time here>  ... problem solved however the issue still exist
