### ISSUE TITLE
Support for FastLegS?

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#57]
Is the FastLegS module still being supported ?

...Just seen that SWIG is no longer supported

**Comment by thadclay** [comment]
SWIG? The template engine? I'm not sure I understand what you asking.

**Comment by gahula** [comment]
I have been using Swig.js / FastLeGs / Node.js for sometime now, among other modules. The environment of Node.js has matured, some contributors no longer have time to focus on development and have chosen to move on to other challenges.

Swig / FastLeGs are big dependencies in any project. PaulArmstrong has stated he no longer has time to pursue the development of SWIG.

Is FastLegS something you will continue to do long term ?

OR

Is there no need to change as there is no major bugs ?

Reference is made to the last time it was updated.
