### ISSUE TITLE
OR

### ISSUE THREAD

**Issue by dvv** [didit-tech/FastLegS#7]
Hi!

I see no support for `OR`-ing conditions. How'd you suggest to work it around?

TIA,
--Vladimir

**Comment by malkomalko** [comment]
Vlad,

Or is about the only query condition that's not setup right now.  I will think about a good way to implement this, but suggestions and contributions are always welcome.

Thanks!

**Comment by dvv** [comment]
Frankly, over time thinking, I start to count adding `or` as opening the Pandora box ;)

**Comment by monokrome** [comment]
Same way AND works? :)
