### ISSUE TITLE
create table

### ISSUE THREAD

**Issue by dvv** [didit-tech/FastLegS#8]
Hi!

What is the interface to create tables? Schema should be derived from fastlegs entities definitions.

TIA,
--Vladimir

**Comment by malkomalko** [comment]
Hi Vlad,

Creating a schema/tables was not part of the initial roadmap for FastLegS as it was primarily built to sit atop an existing database.  Extending it to create your tables under the hood would not be a very hard addition, but we are going to focus on building out some of the additions listed on the issues site as far as Validations/Callbacks/Better Docs.

Hopefully in a few weeks this can be fleshed out more and we can start to look to take this a little bit further.  I want to keep this as small and simple as possible while providing an interface that helps people get off the ground quickly.

Thanks!

**Comment by dvv** [comment]
I see. np
