### ISSUE TITLE
mongo-style conditions

### ISSUE THREAD

**Issue by dvv** [didit-tech/FastLegS#9]
Hi!

Wonder if you could consider using mondodb style for search conditions/directives? That way people could keep their business tier intact while switching sql/nosql backend.

In turn, in [underscore-data](/dvv/underscore-data) we have tools to parse querystrings down to mongo conditions. Gluing these two solutions, one could describe/get his queries in textual form, say: GET /Foo?name=a&email=re:foo,dob<1990&limit(10)&sort(-name) ...

Feasible to have?

TIA,
--Vladimir

**Comment by malkomalko** [comment]
just very quickly.. do you mean {"$in": ['foo','bar'] } instead of 'field.in': ['foo','bar'] ?

**Comment by dvv** [comment]
rather `{ field: { $in: ['foo','bar'] } }`, i suppose. This also has an advantage to disambiguate `.` which is perfectly valid char in field names, IIRC.
